### ISSUE TITLE
Typo in example of scrolling hint

### ISSUE THREAD

**Issue by minipai** [LeaVerou/play.csssecrets.io#1]
Hi, hope here's right place to report issue of example.

Seems there is typo of scrolling hint's example at http://dabblet.com/gist/20205b5fcdd834461e80 which is redirected from http://play.csssecrets.io/scrolling-hints

current: 

```
background: linear-gradient(white 15px, hsla(0,0%,100%,0)) 100% 50px,
```

maybe this is more correct

```
background: linear-gradient(white 15px, hsla(0,0%,100%,0)) 0 0 / 100% 50px,
```

**Comment by LeaVerou** [comment]
Should be fixed now, thanks!
